# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='custom_protocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x0f\x63ustom_protocol\"\x88\x03\n\x08\x45nvelope\x12,\n\x04type\x18\x01 \x01(\x0e\x32\x1e.custom_protocol.Envelope.Type\x12\'\n\x05hello\x18\x02 \x01(\x0b\x32\x16.custom_protocol.HelloH\x00\x12:\n\x0ftopology_update\x18\x03 \x01(\x0b\x32\x1f.custom_protocol.TopologyUpdateH\x00\x12,\n\x08\x66low_mod\x18\x04 \x01(\x0b\x32\x18.custom_protocol.FlowModH\x00\x12\x34\n\x0c\x66low_request\x18\x05 \x01(\x0b\x32\x1c.custom_protocol.FlowRequestH\x00\x12*\n\x05\x65rror\x18\x06 \x01(\x0b\x32\x19.custom_protocol.ErrorMsgH\x00\"Q\n\x04Type\x12\t\n\x05HELLO\x10\x00\x12\x13\n\x0fTOPOLOGY_UPDATE\x10\x01\x12\x0c\n\x08\x46LOW_MOD\x10\x02\x12\x10\n\x0c\x46LOW_REQUEST\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x42\x06\n\x04\x62ody\")\n\x05Hello\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\"?\n\x0eTopologyUpdate\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\x12\x19\n\x11\x62oundary_switches\x18\x02 \x03(\t\"\xb0\x01\n\x0b\x46lowRequest\x12\x13\n\x0bsrc_cluster\x18\x01 \x01(\x05\x12\x13\n\x0b\x64st_cluster\x18\x02 \x01(\x05\x12\x43\n\x0cmatch_fields\x18\x03 \x03(\x0b\x32-.custom_protocol.FlowRequest.MatchFieldsEntry\x1a\x32\n\x10MatchFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xa3\x01\n\x07\x46lowMod\x12\x12\n\ncluster_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x63tions\x18\x02 \x03(\t\x12?\n\x0cmatch_fields\x18\x03 \x03(\x0b\x32).custom_protocol.FlowMod.MatchFieldsEntry\x1a\x32\n\x10MatchFieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"(\n\x08\x45rrorMsg\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\tb\x06proto3'
)



_ENVELOPE_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='custom_protocol.Envelope.Type',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HELLO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TOPOLOGY_UPDATE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOW_MOD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FLOW_REQUEST', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=338,
  serialized_end=419,
)
_sym_db.RegisterEnumDescriptor(_ENVELOPE_TYPE)


_ENVELOPE = _descriptor.Descriptor(
  name='Envelope',
  full_name='custom_protocol.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='custom_protocol.Envelope.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hello', full_name='custom_protocol.Envelope.hello', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topology_update', full_name='custom_protocol.Envelope.topology_update', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flow_mod', full_name='custom_protocol.Envelope.flow_mod', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flow_request', full_name='custom_protocol.Envelope.flow_request', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='custom_protocol.Envelope.error', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENVELOPE_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='body', full_name='custom_protocol.Envelope.body',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=35,
  serialized_end=427,
)


_HELLO = _descriptor.Descriptor(
  name='Hello',
  full_name='custom_protocol.Hello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_id', full_name='custom_protocol.Hello.node_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='custom_protocol.Hello.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=470,
)


_TOPOLOGYUPDATE = _descriptor.Descriptor(
  name='TopologyUpdate',
  full_name='custom_protocol.TopologyUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='custom_protocol.TopologyUpdate.cluster_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boundary_switches', full_name='custom_protocol.TopologyUpdate.boundary_switches', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=535,
)


_FLOWREQUEST_MATCHFIELDSENTRY = _descriptor.Descriptor(
  name='MatchFieldsEntry',
  full_name='custom_protocol.FlowRequest.MatchFieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='custom_protocol.FlowRequest.MatchFieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='custom_protocol.FlowRequest.MatchFieldsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=714,
)

_FLOWREQUEST = _descriptor.Descriptor(
  name='FlowRequest',
  full_name='custom_protocol.FlowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='src_cluster', full_name='custom_protocol.FlowRequest.src_cluster', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst_cluster', full_name='custom_protocol.FlowRequest.dst_cluster', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='match_fields', full_name='custom_protocol.FlowRequest.match_fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FLOWREQUEST_MATCHFIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=538,
  serialized_end=714,
)


_FLOWMOD_MATCHFIELDSENTRY = _descriptor.Descriptor(
  name='MatchFieldsEntry',
  full_name='custom_protocol.FlowMod.MatchFieldsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='custom_protocol.FlowMod.MatchFieldsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='custom_protocol.FlowMod.MatchFieldsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=664,
  serialized_end=714,
)

_FLOWMOD = _descriptor.Descriptor(
  name='FlowMod',
  full_name='custom_protocol.FlowMod',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster_id', full_name='custom_protocol.FlowMod.cluster_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='actions', full_name='custom_protocol.FlowMod.actions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='match_fields', full_name='custom_protocol.FlowMod.match_fields', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FLOWMOD_MATCHFIELDSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=717,
  serialized_end=880,
)


_ERRORMSG = _descriptor.Descriptor(
  name='ErrorMsg',
  full_name='custom_protocol.ErrorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='custom_protocol.ErrorMsg.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reason', full_name='custom_protocol.ErrorMsg.reason', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=882,
  serialized_end=922,
)

_ENVELOPE.fields_by_name['type'].enum_type = _ENVELOPE_TYPE
_ENVELOPE.fields_by_name['hello'].message_type = _HELLO
_ENVELOPE.fields_by_name['topology_update'].message_type = _TOPOLOGYUPDATE
_ENVELOPE.fields_by_name['flow_mod'].message_type = _FLOWMOD
_ENVELOPE.fields_by_name['flow_request'].message_type = _FLOWREQUEST
_ENVELOPE.fields_by_name['error'].message_type = _ERRORMSG
_ENVELOPE_TYPE.containing_type = _ENVELOPE
_ENVELOPE.oneofs_by_name['body'].fields.append(
  _ENVELOPE.fields_by_name['hello'])
_ENVELOPE.fields_by_name['hello'].containing_oneof = _ENVELOPE.oneofs_by_name['body']
_ENVELOPE.oneofs_by_name['body'].fields.append(
  _ENVELOPE.fields_by_name['topology_update'])
_ENVELOPE.fields_by_name['topology_update'].containing_oneof = _ENVELOPE.oneofs_by_name['body']
_ENVELOPE.oneofs_by_name['body'].fields.append(
  _ENVELOPE.fields_by_name['flow_mod'])
_ENVELOPE.fields_by_name['flow_mod'].containing_oneof = _ENVELOPE.oneofs_by_name['body']
_ENVELOPE.oneofs_by_name['body'].fields.append(
  _ENVELOPE.fields_by_name['flow_request'])
_ENVELOPE.fields_by_name['flow_request'].containing_oneof = _ENVELOPE.oneofs_by_name['body']
_ENVELOPE.oneofs_by_name['body'].fields.append(
  _ENVELOPE.fields_by_name['error'])
_ENVELOPE.fields_by_name['error'].containing_oneof = _ENVELOPE.oneofs_by_name['body']
_FLOWREQUEST_MATCHFIELDSENTRY.containing_type = _FLOWREQUEST
_FLOWREQUEST.fields_by_name['match_fields'].message_type = _FLOWREQUEST_MATCHFIELDSENTRY
_FLOWMOD_MATCHFIELDSENTRY.containing_type = _FLOWMOD
_FLOWMOD.fields_by_name['match_fields'].message_type = _FLOWMOD_MATCHFIELDSENTRY
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE
DESCRIPTOR.message_types_by_name['Hello'] = _HELLO
DESCRIPTOR.message_types_by_name['TopologyUpdate'] = _TOPOLOGYUPDATE
DESCRIPTOR.message_types_by_name['FlowRequest'] = _FLOWREQUEST
DESCRIPTOR.message_types_by_name['FlowMod'] = _FLOWMOD
DESCRIPTOR.message_types_by_name['ErrorMsg'] = _ERRORMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Envelope = _reflection.GeneratedProtocolMessageType('Envelope', (_message.Message,), {
  'DESCRIPTOR' : _ENVELOPE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:custom_protocol.Envelope)
  })
_sym_db.RegisterMessage(Envelope)

Hello = _reflection.GeneratedProtocolMessageType('Hello', (_message.Message,), {
  'DESCRIPTOR' : _HELLO,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:custom_protocol.Hello)
  })
_sym_db.RegisterMessage(Hello)

TopologyUpdate = _reflection.GeneratedProtocolMessageType('TopologyUpdate', (_message.Message,), {
  'DESCRIPTOR' : _TOPOLOGYUPDATE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:custom_protocol.TopologyUpdate)
  })
_sym_db.RegisterMessage(TopologyUpdate)

FlowRequest = _reflection.GeneratedProtocolMessageType('FlowRequest', (_message.Message,), {

  'MatchFieldsEntry' : _reflection.GeneratedProtocolMessageType('MatchFieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FLOWREQUEST_MATCHFIELDSENTRY,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:custom_protocol.FlowRequest.MatchFieldsEntry)
    })
  ,
  'DESCRIPTOR' : _FLOWREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:custom_protocol.FlowRequest)
  })
_sym_db.RegisterMessage(FlowRequest)
_sym_db.RegisterMessage(FlowRequest.MatchFieldsEntry)

FlowMod = _reflection.GeneratedProtocolMessageType('FlowMod', (_message.Message,), {

  'MatchFieldsEntry' : _reflection.GeneratedProtocolMessageType('MatchFieldsEntry', (_message.Message,), {
    'DESCRIPTOR' : _FLOWMOD_MATCHFIELDSENTRY,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:custom_protocol.FlowMod.MatchFieldsEntry)
    })
  ,
  'DESCRIPTOR' : _FLOWMOD,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:custom_protocol.FlowMod)
  })
_sym_db.RegisterMessage(FlowMod)
_sym_db.RegisterMessage(FlowMod.MatchFieldsEntry)

ErrorMsg = _reflection.GeneratedProtocolMessageType('ErrorMsg', (_message.Message,), {
  'DESCRIPTOR' : _ERRORMSG,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:custom_protocol.ErrorMsg)
  })
_sym_db.RegisterMessage(ErrorMsg)


_FLOWREQUEST_MATCHFIELDSENTRY._options = None
_FLOWMOD_MATCHFIELDSENTRY._options = None
# @@protoc_insertion_point(module_scope)
